* More iteration protocols

Generate all parts.

Generate all partitions.

Generate all left and right inverses of a map.

              ; also eachmono(A, B), eachepi(A, B)
randmap(A, B) ; also randmono(A, B), randepi(A, B)

Maps factor. Maps have sections and retractions.

A TinyRelation from a TinySet A to a TinySet B is a part of A тип B with
canonical projections or something like that. Is a part of a canonical
product, maybe.

                   ; eachorder(A, B)
randrelation(A, B) ; randorder(A, B)

Maybe diagrelation(A)? and diag(R)::TinySet? Or what?

* Should there be canonical maps?

Should there be canonical inclusions, tinymap(top(3), top(8)),
tinymap(tinyset(1,2,3), top(8)) as inclusions to top(8),
tinymap(top(3), top(5)), tinymap(tinyset(1,2,3), tinyset(1,2,3,4,5))
to top(5), and generally.

Then there are the universal maps tinymap(tinyset(), A) for any A and
tinymap(A, tinyset(1)) also for any A.

The ambiguity is not real, because tinymap(tinyset(), A) is the
canonical inclusion when A is a canonical part, and tinymap(A,
tinyset(1)) is the canonical inclusion when A is 1.

* Determines, is determined by

Factors through, all that ETCS.

Generalized elements.
